version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: silverbroccoli
    volumes:
      - "./build/mongodb/db:/data/db"
    ports:
      - "27017:27017"